#!/bin/sh
set -e

case "$1" in
    remove)
        echo "removed"
        rm /etc/systemd/system/calendard.service
        rm -r /opt/calendar-daemon/config
    ;;

    *)
        echo "postrm called with unknown argument \`$1'"
        exit 0
    ;;
esac

exit 0